### ISSUE TITLE
XOr implementation

### ISSUE THREAD

**Issue by andrrizzi** [keleshev/schema#106]
First of all, this library is awesome.

I've implemented a `XOr` class for exclusive schemas (shamelessly copying from the `Or` class). Maybe this is naively wrong, but so far this has worked as expected.

``` python
class XOr(And):

    def validate(self, data):
        accepted = False
        x = SchemaError([], [])
        for s in [Schema(s, error=self._error) for s in self._args]:
            try:
                validated = s.validate(data)
                if accepted:
                    raise SchemaError(['%r did not validate %r' % (self, data)],
                                      [self._error])
                accepted = True
            except SchemaError as _x:
                x = _x
        if not accepted:
            raise SchemaError(['%r did not validate %r' % (self, data)] + x.autos,
                              [self._error] + x.errors)
        return validated
```

If you are interested in this, I can open a PR.

**Comment by skorokithakis** [comment]
This is interesting, but I'm afraid it may be misnamed. I would expect `xor(1, 0, 1)` to be `True`, for example, whereas this returns `False`. Maybe it should be named `OnlyOne` or something like that, instead?

**Comment by andrrizzi** [comment]
> Maybe it should be named `OnlyOne`

Good point. `OnlyOne` sounds great.

**Comment by andrrizzi** [comment]
After some more rigorous testing, this doesn't work. It was working only in my particular case, and I don't see an easy way to implement this without changing the way `Schema` currently does its job. To be more precise, I was hoping to do something like
```python
my_schema = Schema({OnlyOne('either_this', 'or_this'): str, 'long': int, 'common': float, 'schema': float})
```
as a simplification of
```python
common_schema = {'long': int, 'common': float, 'schema': float}
either_this_schema = {'either_this': str}
either_this_schema.update(common_schema)
or_this_schema = {'or_this': str}
or_this_schema.update(common_schema)
my_schema = Schema(Or(either_this_schema, or_this_schema))
```
I've now fallen back to the second solution.

Feel free to close this (although I think it would still be nice to have something like this in the future).
