### ISSUE TITLE
Subclass SchemaError for default errors such as 'Wrong keys', 'Missing keys'  'Wrong Type'

### ISSUE THREAD

**Issue by bernalrs** [keleshev/schema#111]
I would like to suggest a simple change that would see the introduction of some new Error/Exception derived from SchemaError which would serve the purpose.

As of verson 0.6.1:

1.  `raise SchemaError('Wrong keys %s in %r' % (s_wrong_keys, data),  e.format(data) if e else None)` 
2. ` raise SchemaError('Missing keys: ' + s_missing_keys, e)`
3. `SchemaError('%r should be instance of %r' % (data, s.__name__), e.format(data) if e else None)`

into 

1.  `class SchemaWrongKeyError(SchemaError):`
2.  `class` SchemaMissingkeysError(SchemaError):
3. `class SchemaUnexpectedTypeError`(SchemaError)

Thanks

**Comment by skorokithakis** [comment]
As long as these exceptions inherit from `SchemaError`, this looks good to me. Is there any possibility that something could be adversely impacted?

**Comment by bernalrs** [comment]
As long as we do not change the error message we should be OK. This should allow developers to catch specific exception and re-throw them when using this library in the application code.

**Comment by bernalrs** [comment]
Might be worth adding these new type in the README.md do you agree ?

**Comment by skorokithakis** [comment]
Yes :( I forgot about that and already released 0.6.2... Would you like to do the honours of documenting the errors?
