### ISSUE TITLE
Question: how to define schema for recursive structure?

### ISSUE THREAD

**Issue by AlexandreDecan** [keleshev/schema#119]
Hello, 

I've a question about the definition of a schema for a recursive structure. Say for example I want to encode a ``person`` which has a firstname, a lastname, and a list of children which are ``person`` too.
How can I do that?

Basically, I would like to do: 
```python
person = {'firstname': str, 'lastname': str, Optional('children'): [person]}
```

Obviously, this does not work. Is there a solution?

Currently, I do something like: 
```python
person = {'firstname': str, 'lastname': str}
person[Optional('children')] = [person]
```

... but I find it not really readable...

**Comment by skorokithakis** [comment]
I was just going to post that but you updated the post. Does the recursion you tried work well? I think that is the most reasonable way to do it, currently. I agree that it's not very readable, but that's a Python issue, not a schema issue...

**Comment by AlexandreDecan** [comment]
Yes, it works. But in case of a validation error, the error message is not very useful/accurate, but that's another issue ;-)

Btw, thanks for your answer!

**Comment by miso-belica** [comment]
@keleshev Would be nice to have this in documentation. I used library [voluptuous](https://github.com/alecthomas/voluptuous/pull/151) just because I thought this is not possible with Schema.

**Comment by AlexandreDecan** [comment]
Indeed. I also looked at voluptuous, but I didn't like much its "*non pythonic*" approach to declare schema.

**Comment by RagingRoosevelt** [comment]
Wait, so does this actually work?  I tried doing (for example)

```python
[...]

Person = Schema(
    {
        'name': str
        ,'gender': str
    }
    , name='Person', as_reference=True
)
person['children'] = [person]
```
and I got an error message of `TypeError: 'Schema' object does not support item assignment`.  Am I missing something, or was this just a proposed way to do this?

**Comment by AlexandreDecan** [comment]
Create and store the inner dict separately, following this idea:  

```
person = dict()
person.update({'name': str, 'gender': str, 'children': [person])
```

**Comment by RagingRoosevelt** [comment]
Ah, ok, that makes sense.  

For anyone finding this in the future:

```python
>>>from schema import Schema
>>>person = dict()
>>>Person = Schema(person)
>>>person.update({'name': str, 'children': [Person]})

>>>print(Person)
Schema({'name': <class 'str'>, 'children': [Schema({...})]})

>>>print(Person.schema.get('children'))
[Schema({'name': <class 'str'>, 'children': [Schema({...})]})]
```
