### ISSUE TITLE
Custom error message doesn't get formatted if flavor==CALLABLE

### ISSUE THREAD

**Issue by M3t0r** [keleshev/schema#132]
```
Schema(lambda i: i == 5, error="Formatstring: {}").validate(12)
```
produces an exception with the message "Formatstring: {}" and not "Formatstring: 12"

I had to change line [309](https://github.com/keleshev/schema/blob/master/schema.py#L309) to

    raise SchemaError('%s(%r) should evaluate to True' % (f, data), e.format(data))

to get it working as intended.

You're also missing the documentation for this feature all together. Took me a while to figure out. And #4 is still open, too.

**Comment by sritchie** [comment]
This is still a problem today! I'll send a PR...

**Comment by sritchie** [comment]
Ah, I see it was fixed six days ago. Thank you!
