### ISSUE TITLE
(crazy) feature idea: @validate_args() decorator

### ISSUE THREAD

**Issue by kurtbrose** [keleshev/schema#136]
https://gist.github.com/kurtbrose/8633b06f0bced5cba52a7a8b1d763ae8

```python
    @validate_args(a=[str], b=int, c=lambda v: v is not None)
    def foo(a, b, c, d):
        return a, b, c, d

    try:
        foo('cat', 1, 2, 3)
    except ValueError as ve:
        print ve

    try:
        foo([1], b=2, c=None, d=12)
    except ValueError as ve:
        print ve
    
    foo(['cat', 'dog'], 2, 3, 4)
```

Intercepts kwargs passed to `@validate_args()` and passes them through the validate() of the corresponding schema before being passed on to the wrapped function.

Failed validates are gathered together and raised as a single exception.

**Comment by skorokithakis** [comment]
This kind of seems like a reimplementation of optional typing, so I'd rather leave that for mypy.

**Comment by kurtbrose** [comment]
I agree this is very out there :-)
Even if mypy didn't exist it might be diluting the focus of schema to add this kind of feature.

**Comment by kurtbrose** [comment]
I'm going to close this because I agree it doesn't belong in schema
