### ISSUE TITLE
Can we get a release for 2017?

### ISSUE THREAD

**Issue by mahmoud** [keleshev/schema#138]
Not to be a nag, we all love schema! At least a few PRs have been merged since September 2016 and I think we would love to see a release with all the new features. Telling people to pip install from GitHub just doesn't have the same ring to it ;)

Thanks for all your hard work!

**Comment by skorokithakis** [comment]
Good call, 0.6.6 is live, thank you!

**Comment by 5amfung** [comment]
I tried to use Const but realized it's not in 0.6.6.  Any suggestion on a workaround for now unless there will be another push to pypi soon?  Thanks.

**Comment by skorokithakis** [comment]
I have released (the unsemantically versioned, I now realize) 0.6.7. Please let me know if you find any problems with it.
