### ISSUE TITLE
hash(Optional(foo)) should equal hash(foo)

### ISSUE THREAD

**Issue by kurtbrose** [keleshev/schema#139]
```python
{schema.Optional(1): 2, schema.Optional(1): 3}

schema.Schema({schema.Optional(1): 2, schema.Optional(1): 3}).validate({1:3})
```

If Optional(foo) had a hash based on foo, then Optional(const) would overwrite itself as a dict key, and you wouldn't get race condition / undefined behavior from the above construct.

Also, it would make this kind of non-sensical schema impossible:

```python
{schema.Optional([]): 2}
```

One way to achieve this would be to switch schema objects into attrs instances.
https://attrs.readthedocs.io/en/stable/

This would get "free" `__eq__`, `__hash__`, `__repr__`, and `__init__` that behave as expected.  Also, if desired all classes could be switched to use `__slots__` very easily.

This would add a dependency to schema, but might be worth it.

**Comment by skorokithakis** [comment]
Hmm, this is quite a serious bug, thanks for the report. As much as I love the `attrs` library, I don't see adding the dependency as worth it, as it's just a few short methods to implement. Would you be interested in submitting a PR?

**Comment by kurtbrose** [comment]
Sure, I'd be happy to contribute.

**Comment by kurtbrose** [comment]
I think the simplest approach is just to override `__eq__` and `__hash__` on Optional().

There are still some weird behaviors, since all Schema's are hash-able, you could technically stick any of them as dict keys.  e.g. `schema.Schema({schema.Or(1,2): 'cat', 2: 'dog'}).validate({2: 'cat'})`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kurtrose/sky/sky/src/schema/schema.py", line 254, in validate
    raise SchemaError([k] + x.autos, [e] + x.errors)
schema.SchemaError: Key '2' error:
'dog' does not match 'cat'
```

I think it's very hard to say "this schema will or won't collide with that other schema".

Maybe the way to handle Or() And() etc is to change the way dict keys that are Schema objects are handled.  If key.validate(k) works, but val.validate(v) fails, try going through the other keys in the dict to see if any of them might match instead of raising the exception immediately.


```python
>>> schema.Schema({schema.And(int, schema.Use(lambda n: n+1)): 'cat'}).validate({2: 'cat'})
{3: 'cat'}
```

**Comment by skorokithakis** [comment]
I really think just overriding `__eq__` and `__hash__` is best, for now, as you suggest. I don't see people using entire `Schema`s as keys, or, if they do, at least I don't see them expecting that they will hash consistently. Due to the way `Optional` is used, though, I think it's very reasonable that people will expect consistent hashing there.

**Comment by kurtbrose** [comment]
Yea, makes sense.  I'll stick to the simple change.

I guess there is a well-defined order of operations for cases like this:

```python
>>> schema.Schema({int: 'cat', 1:'dog'}).validate({1: 'dog', 2: 'cat', 3: 'cat'})
{1: 'dog', 2: 'cat', 3: 'cat'}
```

**Comment by kurtbrose** [comment]
https://github.com/keleshev/schema/pull/140

**Comment by kurtbrose** [comment]
change is merged so I guess this is resolved :-)
