### ISSUE TITLE
{'a':int} cannot match {'b':'x', 'a':1}

### ISSUE THREAD

**Issue by reedboat** [keleshev/schema#15]
s = Schema({'a':int})
 print s.validate({'c':'x', 'a':1})

It reports that 'a' is required, while a has been provided.

**Comment by sjakobi** [comment]
With the current master (e94b7144f3016654d1360eb1c070fd2db0d54a43):

```python
>>> s = Schema({'a': int})
>>> s.validate({'c':'x','a': 1})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "schema.py", line 153, in validate
    e)
schema.SchemaError: Wrong keys 'c' in {'a': 1, 'c': 'x'}
```

This seems to be fixed and can be closed.
