### ISSUE TITLE
Schema({<key_type>: <value_type>}).is_valid({}) returns False?

### ISSUE THREAD

**Issue by bhyde** [keleshev/schema#167]
When using a dictionary to manage set of objects it's a bit subtle to include the empty set.
```
>>> Schema({int:int}).is_valid({1:2})
True
>>> Schema({int:int}).is_valid({})
False
>>> 
```
You need to write ```Schema(Or({int:int}, {}))```

But maybe I'm not looking at this right.

It seems inconsistent with the handling for lists.
```
>>> Schema([int]).is_valid([1])
True
>>> Schema([int]).is_valid([])
True
```
I'd think this is a bug that has matured into a feature.  A tips and tricks addition to the documentation would be sweet though.

**Comment by skorokithakis** [comment]
I agree, this is inconsistent. As you say, it's been there so long that people probably rely on it now, so I will add it to the docs.

**Comment by bhyde** [comment]
![present](https://user-images.githubusercontent.com/19701/46246217-25366f00-c3c8-11e8-94cc-293dbb7b200c.gif)
