### ISSUE TITLE
Option to Allow Extra Keys in Schema

### ISSUE THREAD

**Issue by rmorshea** [keleshev/schema#189]
The ability to allow extra keys makes it very easy to use `And` to compose a more complex schema from individual pieces. See #188 and [this comment](https://github.com/keleshev/schema/issues/188#issuecomment-455806593) which describes how to trivially solve it with an `allow_extra_keys=True` flag in `Schema`.

**Comment by skorokithakis** [comment]
This is fixed with `ignore_extra_keys`, correct? I will close, feel free to reopen if not.
