### ISSUE TITLE
Disabling type checking

### ISSUE THREAD

**Issue by abbas-aghamirzaei** [keleshev/schema#190]
hi.
how can I disable type checking(for performance)?
I want to only check the structure of dictionary. Is it possible?
thanks.

**Comment by abbas-aghamirzaei** [comment]
for example consider the following schema
conf_schema = Schema({
    'info': {
        'conf_one': And(Or(Use(int,float))),
        'conf_two': And(Use(str)),
        'conf_three': And(Use(bool)),
        Optional('optional_conf'): And(Use(str))
    }
})
I want to only check the existence of fields by schema(your library), type of fields is not important for me.

**Comment by skorokithakis** [comment]
So don't include the types in your schema, I'm not sure what the problem is.

**Comment by abbas-aghamirzaei** [comment]
no problem, thank you.

**Comment by skorokithakis** [comment]
No problem! You can use `object` if you don't want type checks to take place. If you want performance, though, you may have to use something C-based or another alternative.
