### ISSUE TITLE
Question: Schema for list of strings with regex

### ISSUE THREAD

**Issue by ngfgrant** [keleshev/schema#195]
Hey - first of all great project thank you for all the work.

I have been banging my head against the wall for something that I am absolutely sure is possible but looking for some pointers.

```yaml

___
...
emails:
  - email@test.comm
  - email2@test.comm
...
```

```python 
...

def _email_regex():
    return r'(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)'


schema = Schema(
    {
...
        'emails': [how can I validate the list of strings matches the _email_regex()],
...
    }

```

I can easily validate that `emails` is a list but I would like to go a step further and check that the value of the items in the list are strings and meet the regex defined above. Seemed to work very easily when the values are just a single string but being a list I think I am missing something.

Any help gratefully received.

**Comment by bskari** [comment]
Use schema.And, something like this:

```python
from schema import And

EMAIL_REGEX = re.compile(r'(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$)')

def validate_email_list(email_list):
    return all((EMAIL_REGEX.match(email) for email in email_list))

schema = Schema({
    "emails": And([str], validate_email_list)
})
```

**Comment by ngfgrant** [comment]
Amazing thanks @bskari - I got this working and will put submit a PR for this as a full worked example which might help the docs?

**Comment by bskari** [comment]
@ngfgrant Glad it worked! I'm not a maintainer, but you're welcome to submit a PR for the docs. I don't have any say as to whether or not it would be accepted though.
