### ISSUE TITLE
Update pypi version to 0.7.2?

### ISSUE THREAD

**Issue by sklarsa** [keleshev/schema#197]
I'd really like to start using Hooks, but the latest version of this lib in pypi is 0.6.8.  Is there a scheduled release date for 0.7.2?

**Comment by skorokithakis** [comment]
0.7.2 of which library?

**Comment by sklarsa** [comment]
https://pypi.org/project/schema/
https://github.com/keleshev/schema/releases/tag/v0.7.2

**Comment by skorokithakis** [comment]
This looks like a mistaken tag, the next release will probably be 0.6.9 or 0.7.0. We can release a new version, though, yep.

**Comment by sklarsa** [comment]
Got it... thanks! Can you provide any kind of timeframe for that?

**Comment by skorokithakis** [comment]
I can do it now, if master is stable. Have you used it at all?

**Comment by sklarsa** [comment]
No, I'm integrating it into a project now and want to use hooks to collect certain pieces of information as the schema gets validated

**Comment by skorokithakis** [comment]
Are you using HEAD for that project? I can release 0.7 soon.

**Comment by sklarsa** [comment]
No, but I can.  I'm using poetry which doesn't have the best support for url dependencies, but I can live with that for a little bit

**Comment by skorokithakis** [comment]
Released [0.7.0](https://pypi.org/project/schema/0.7.0/), please let me know if there are any problems!
