### ISSUE TITLE
Are Enums working?

### ISSUE THREAD

**Issue by eulogio-gutierrez** [keleshev/schema#235]
Hi there,

running this:

```
from schema import Schema
import json

print(json.dumps(Schema({"letters": ["a", "b", "c"]}).json_schema("https://example.com/my-schema.json")))
```

gives me: 

`{"type": "object", "properties": {"letters": {"type": "array", "items": {"enum": ["a", "b", "c"]}}}, "required": ["letters"], "additionalProperties": false, "$id": "https://example.com/my-schema.json", "$schema": "http://json-schema.org/draft-07/schema#"}`

but I was expecting to get either this:

`{"type": "object", "properties": {"letters": {"type": "string", "enum": ["a", "b", "c"]}}, "required": ["letters"], "additionalProperties": false, "$id": "https://example.com/my-schema.json", "$schema": "http://json-schema.org/draft-07/schema#"}`

or this:

`{"type": "object", "properties": {"letters": {"enum": ["a", "b", "c"]}}, "required": ["letters"], "additionalProperties": false, "$id": "https://example.com/my-schema.json", "$schema": "http://json-schema.org/draft-07/schema#"}`

What is the correct way to use Enums?

Thanks
Eulogio

**Comment by skorokithakis** [comment]
Hmm, @dblanchette, do you think you could answer this? I'm not very familiar with JSONSchema support, sadly, as I've never used it.

**Comment by dblanchette** [comment]
@eulogio-gutierrez You can get enums by using the keyword `Or`

```python
from schema import Schema, Or
import json

print(json.dumps(Schema({"letters": Or("a", "b", "c")}).json_schema("https://example.com/my-schema.json"), indent=4, separators=[",", ": "]))
```` 

Will give 
```json
{
    "type": "object",
    "properties": {
        "letters": {
            "enum": [
                "a",
                "b",
                "c"
            ]
        }
    },
    "required": [
        "letters"
    ],
    "additionalProperties": false,
    "$id": "https://example.com/my-schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#"
}
```

If you already have a list object, you can unpack it using `*`

This code prints the same result as above
```python
from schema import Schema, Or
import json

choices = ["a", "b", "c"]
print(json.dumps(Schema({"letters": Or(*choices)}).json_schema("https://example.com/my-schema.json"), indent=4, separators=[",", ": "]))
```
