### ISSUE TITLE
is there conditional schema?

### ISSUE THREAD

**Issue by ftian1** [keleshev/schema#242]
I want to express a dependency relationship between yaml items, 

such as:

gender: male
beard:                # optional, only needed when gender value is male.
  color: golden

seems this repo doesn't support this semantic? or am i missing sth?

**Comment by skorokithakis** [comment]
This is not supported, unfortunately.

**Comment by monstermichl** [comment]
Would it be possible to pass the already evaluated values to a lambda function of a schema property? This way the user could write his own conditional evaluation method.
