### ISSUE TITLE
Why was 0.7.3 yanked off PyPi?

### ISSUE THREAD

**Issue by andschwa** [keleshev/schema#250]
I unfortunately took a dependency after July and so am locked to 0.7.3, which while still the latest on GitHub, has been yanked from PyPi. I'm trying to figure out if this was a mistake that is shortly to be corrected, or if I should go through the process of downgrading my packages' version requirement.

![image](https://user-images.githubusercontent.com/2226434/101525000-8dd1ec80-393f-11eb-89a5-02a10148c352.png)

Thanks!

**Comment by skorokithakis** [comment]
Hmm, good question. It was a while ago, so I don't remember why. It'd have to be some error in the code, but I don't know what, and I can't find any issues or PRs talking about it, which I'm sure should exist.

**Comment by skorokithakis** [comment]
Ah:

 * Yanked by: Stavros with a role: owner.
 * Reason: There is a regression in error formatting.

**Comment by skorokithakis** [comment]
If you don't care about error formatting you should be good with 0.7.3.

**Comment by andschwa** [comment]
Ah, thank you! My issue was that whatever combination of poetry and pip I’m using failed to install after the yank because I’d specified ^0.7.3 and it would then fail to find it. Why that is, I don’t know, but it was easier to just drop all the versions to 0.7.2 and update the lock files.
