### ISSUE TITLE
Use of schema in astroquery

### ISSUE THREAD

**Issue by jwoillez** [keleshev/schema#31]
@halst - The project https://github.com/astropy/astroquery would benefit from using schema. The simplest approach would be to copy schema.py, as well as the MIT license.

I've setup a branch for you to have a look:
https://github.com/jwoillez/astroquery/tree/schema

Schema itself is at:
https://github.com/jwoillez/astroquery/blob/schema/astroquery/utils/schema.py

The license:
https://github.com/jwoillez/astroquery/blob/schema/licenses/SCHEMA.rst

Does this look correct to you?

Thanks! Really love schema!

**Comment by sjakobi** [comment]
Seems like this issue can be closed.

The project includes Schema here: https://github.com/astropy/astroquery/blob/189064037d57a29b8e867cdaf3e06568146fcaf4/astroquery/utils/schema.py

**Comment by skorokithakis** [comment]
In general, pinning to minor revisions is safe, since they'll always be backwards-compatible. At the very least, one can specify a dependency to `~=0.3.1` and it will upgrade to new patch revisions automatically.
