### ISSUE TITLE
Needless call to eval in setup.py

### ISSUE THREAD

**Issue by moltenform** [keleshev/schema#318]
I prefer to get rid of calls to `eval` for security reasons,

Especially in a setup.py file where one wouldn't expect code to run just by importing the file.

If someone malicious were to make a file named `schema.py` they could get an arbitrary line of code to run.

Let's see if we can change the line 

```
 if line.startswith("__version__ ="):
            version = eval(line.split("=", 1)[1])
            break
```

to
 
```
 if line.startswith("__version__ ="):
            version = line.split("=", 1)
            version = version.replace('"', '').replace("'", '')
            version = version.strip()
            break
```

**Comment by skorokithakis** [comment]
No reason why we can't, would you like to submit a PR?

**Comment by moltenform** [comment]
Thanks!

**Comment by skorokithakis** [comment]
Thank you!
