### ISSUE TITLE
Is there a way to automatically document a schema using Sphinx?

### ISSUE THREAD

**Issue by thedannymarsh** [keleshev/schema#323]
Pretty much the title. Provide documentation to users on the possible options that they can use for a config file that is validated with schema.

**Comment by mutricyl** [comment]
you can export your schema to json ( `.json_schema()` )and then read it in sphinx with a dedicated extension like https://sphinx-jsonschema.readthedocs.io/en/latest/index.html

**Comment by thedannymarsh** [comment]
Ok awesome, thanks!
