### ISSUE TITLE
When validating, check if issubclass of type instead of just type

### ISSUE THREAD

**Issue by jmansilla** [keleshev/schema#40]
I have so code that should work both in python 2 and 3, and because of that I'm using instead of strings

future.builtins.str

the type of such a thing is 

future.builtins.types.newstr.BaseNewStr

and because of that, instead of validating the type is used as a callable.

**Comment by sjakobi** [comment]
This seems to be fixed. Please close this.

**Comment by jmansilla** [comment]
Thanks
