### ISSUE TITLE
Wrong behaviour with Optional(basestring): object

### ISSUE THREAD

**Issue by poulainv** [keleshev/schema#44]
```python 
> Schema({Optional('attr1'): 'foo', Optional(basestring): object}).validate({'attr1': 'new_foo'})
{'attr1': 'new_foo'}
```

My use case: any keys should be accepted in the dict. Only condition, if I have `attr1` it must be  `foo`.

**Comment by keleshev** [comment]
https://github.com/erikrose/schema/commit/e36550d3f027bd5c15af194b397c0a546bd84f7b
