### ISSUE TITLE
Broken distribution package

### ISSUE THREAD

**Issue by mbergkvist** [keleshev/schema#58]
The implementation of the `Optional` class is missing from the package at PyPi.

    $ curl https://pypi.python.org/packages/source/s/schema/schema-0.3.1.tar.gz -o schema-0.3.1.tar.gz
    $ tar xzf schema-0.3.1.tar.gz schema-0.3.1/schema.py
    $ tail schema-0.3.1/schema.py
                raise SchemaError('%s(%r) should evaluate to True' % (f, data), e)
            if s == data:
                return data
            else:
                raise SchemaError('%r does not match %r' % (s, data), e)

    class Optional(Schema):

        """Marker for an optional part of Schema."""

And then nothing more.

**Comment by mbergkvist** [comment]
Can someone please upload a working package to PyPi?

**Comment by keleshev** [comment]
> The implementation of the `Optional` class is missing from the package at PyPi.

This is intended. Here's the same file at `0.3.1` tag: https://github.com/keleshev/schema/blob/0.3.1/schema.py

Let me know if you experience any errors while using Schema.

**Comment by mbergkvist** [comment]
My bad, I am using the default support in Optional and didn't realize this was an unreleased feature. I will just bundle schema.py with my project until a new release is available.
