### ISSUE TITLE
Feature Request: Docstrings

### ISSUE THREAD

**Issue by elrond79** [keleshev/schema#63]
I'd love to see support for docstrings/helpstrings/descriptions of some sort.  Not only would this encourage documentation of the schema, but it would allow automated generation of things like argument parsers, and allow us to finally unite all our schema-definition in one place.

**Comment by keleshev** [comment]
Could you elaborate and give an example?

**Comment by elrond79** [comment]
Well, haven't given a lot of thought yet to the exact interface, but maybe something like this:

dino_schema = Schema({
    "Claws": Doc(int, "the number of claws on each hand"),
    "Diet": Doc(Or("meat", "plants", "people"), "what it eats"),
})

The Doc wrappers would be discarded when validating, but would be queryable somehow - given the arbitrary nature schema data, how exactly is a bit of an open question.  Maybe we could do:

>>> dino_schema.doc()
{"Claws": "the number of claws on each hand", "Diet": "what it eats"}
>>> dino_schema.doc()["Claws"]
"the number of claws on each hand"
>>> dino_schema._schema["Diet"].doc()
"what it eats"

**Comment by kosz85** [comment]
You could do that with #64. 
If you assume that we will define restricted name `__doc__` then:
`dino_schema.validate(only='__doc__')`
 could behave like you described, and for other set of namespaces do nothing.
