### ISSUE TITLE
Redundant logic or missing test case?

### ISSUE THREAD

**Issue by sjakobi** [keleshev/schema#75]
I was just fiddling around in the `dict`-part of the `validate` method and noticed the change here (https://github.com/sjakobi/schema/commit/486cb583391084c773db8895ed4d03b93c8be1d9) didn't result in a failing test.

Does anybody know why this logic was necessary in the first place? Is it redundant now?

I'll probably look into this at a later time.

**Comment by skorokithakis** [comment]
That's odd, looks to me like the check for `x` should raise an exception, as it's undefined if there are no keys. Looks like it needs an `x = None` at the top.

**Comment by sjakobi** [comment]
The `x = None` is in line 115.

I've submitted PR #79 with the claim that the dict validation code is in fact overly complicated und redundant.

Let's continue the discussion there! :grinning:
