### ISSUE TITLE
Schema validation quits on first error

### ISSUE THREAD

**Issue by victorandree** [keleshev/schema#8]
Given a simple schema:

```
schema = Schema({
    'name': And(str, lambda s: len(s) <= 50),
    'email': And(str, lambda s: '@' in s)
})
```

If I submit this with bad data for both fields, only one error will be reported:

```
>>> schema.validate({'name': 'Too Long Name', 'email': "invalid email address"})
SchemaError: key 'name is required'
<lambda>('Too Long Name') should evaluate to True
```

I understand that this might be intentional, but in my opinion it hampers the user experience since they have to resubmit and resubmit. Is there a way to get "all" validation errors at once?

**Comment by Firemango** [comment]
Did anyone ever come up with a fix or workaround that is plausible?

**Comment by thatneat** [comment]
Not with Schema. Note that [voluptuous](https://github.com/alecthomas/voluptuous) does have a decent pattern for this where a `MultipleInvalid` exception can wrap multiple `Invalid`s.

**Comment by victorandree** [comment]
I doubt this is going to happen by now. As the author of the issue, I'm closing it.
