### ISSUE TITLE
Inconsistent return types for validate: type(schema) or type(data)?

### ISSUE THREAD

**Issue by sjakobi** [keleshev/schema#83]
I've noted a small inconsistency when validating with iterable and dict schemas:

```python
        if flavor == ITERABLE:
            data = Schema(type(s), error=e).validate(data)
            return type(s)(Or(*s, error=e).validate(d) for d in data)
        if flavor == DICT:
            data = Schema(dict, error=e).validate(data)
            new = type(data)()  # new - is a dict of the validated values
            ...
            return new
```

Briefly, when validating with iterable schemas the return type is that of the schema, when validating with dict schemas it's that of the input.

Personally I think that it's more flexible to have the return type match the one of the input.

Ideas, preferences?

**Comment by skorokithakis** [comment]
I agree with your assessment, but I'm not sure I grasp the implications wholly. In the iterable case, the input may be of one of various types. In the case of the dict, it can only be a dict.

However, it's clear that, in the former case, we should return the type of the input, and we should also be consistent, therefore we should do the same in the case of the dict.

**Comment by sjakobi** [comment]
> In the case of the dict, it can only be a dict.

The type of the data can be any subclass of dict, such as defaultdict or OrderedDict! We even have [a test for that](https://github.com/keleshev/schema/blob/29286c1f9cce20cf70f2b15d9247f2ca6ef1d6c9/test_schema.py#L179-L183)!

I'm not sure whether e.g. list has any subclasses in the wild. But the idea is that one could validate e.g. a SortedList object with a list schema and get a SortedList object back.

**Comment by skorokithakis** [comment]
Ah, that's true. We definitely should change it to your proposal, then.

**Comment by sjakobi** [comment]
Ok, this is an API change though IMO.

**Comment by skorokithakis** [comment]
That's true, someone might rely on the behavior.
