### ISSUE TITLE
Allow formatting for custom error messages

### ISSUE THREAD

**Issue by MaxNoe** [keleshev/schema#98]
I would be hugely helpfull, if one could format the information
which is available for the stanard error messages also into the custom errors.

Idea:

```
from schema import Schema
from os import path

test_existance = Schema(path.exists, error='File "%(data)r" not found!')
```

**Comment by skorokithakis** [comment]
Hmm, what would `data` be in this case? Are you proposing that Schema runs `error.format(data)` before display?

**Comment by MaxNoe** [comment]
Yes. Currently the code for the build in message is:
For example for functions:
```
'%s(%r) should evaluate to True' % (f, data)
```
Or for Use:
```
'%s(%r) raised %r' % (f, data, x)
```
It would be nice if the custom error messages could also use `f`,`data` or `x`.

**Comment by bernalrs** [comment]
I guess we can now close this issue ?
